name: Build

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_version: 1.0.${{github.run_number}}
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build Authenticator.sln  /p:Version=${{env.build_version}} --no-restore
        
      - name: Test with the dotnet CLI
        run: dotnet test

      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: BUILD with number ${{env.build_version}} FAILED!
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.DISCORD_FAILED_BUILDS_WEBHOOK }}
          
      - name: Build passed
        uses: rjstone/discord-webhook-notify@v1
        if: |
          success() && 
          github.event.pull_request.merged == true
        with:
          severity: info
          details: Build ${{env.build_version}} successfully PASSED!
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.DISCORD_PASSED_BUILDS_WEBHOOK }}
